### ISSUE TITLE
Bobs Mods Research

### ISSUE THREAD

**Issue by OvermindDL1** [msakuta/Factorio-LateUpgrades-Mod#1]
Bobs Mods adds a `science-pack-4`, any chance on a soft dependency on bobtech and if `science-pack-4` exists then add it to the extension research?  That is the research that slows me down the most so I would love to have it in as well to continue further into the late game.

In the `./prototypes/technology/common.lua` file, the `createupgrade` function, it should be easy to add the `science-pack-4` there, copied from `science-pack-3` unless a `params.pack_d` (darkblue) exists as a simple one-off change to support it.  His `science-pack-gold` also exists if you wish to use it, though it is just a combination of Science Packs 1, 2, and 3 (not 4, it is 'pre-4' tech) all combined to be used in his alien science lab, which also supports `alien-science-pack-blue`, `alien-science-pack-orange`, `alien-science-pack-purple`, `alien-science-pack-yellow`, `alien-science-pack-green`, and `alien-science-pack-red.  Though those are good for specific purposes I do not think they have any real need unless you want to add in bobsmods extended research for his special alien ammo (which are the major users of those alien sciences based on the type of ammo for the type of color).

Overall, the `science-pack-4` would be a fantastic add to all of the research this mod adds if Bob's Mods `bobtech` mod is installed, and if you wish to add more lategame research then the Bob's Mods bobwarfare has a lot of alien science that it would work well with (in addition to using `science-pack-4`'s) for, say, his special ammo damage upgrades (he has none as I recall so it would be easy to add some there, a very small increase per research I'd recommend considering their existing power).  Could be interesting to even add the color alien science packs in the order above to the existing higher research, they are basically 'unlocked' from biters in the above given order (so until you get to near 100% evolution you will not be getting red yet, but it does unlock the most powerful ammo, though the ammo also requires the red alien drops and a lot of processing to make so it is not an infinite ammo thing).

**Comment by msakuta** [comment]
I think this patch will do it: a252b942556fec5dec35b52c931f0a0e9a49ccb9

If you set `pack_d`, it will use that value. If not, it will copy value of `pack_b`. You can also switch the use of science pack 4 with `EnableBobsSciencePack4` in config.lua. Of course it's automatically disabled if Bob's tech mod is not active.

However, I don't particularly play Bob's mods, and I'm afraid I won't have time to test the balance of the costs, nor test if adding pack-gold etc. would be a good thing (this game needs quite a lot of time to test, you know). If you feel okay with this patch, I'll merge it. If you think tweaking is needed, probably the easiest way for me is to merge your pull request.

**Comment by OvermindDL1** [comment]
Actually that looks great.  As far as balance what you do for vanilla just the same with science-pack-4 is fine so that copy as 'default' is perfect.  :-)

**Comment by msakuta** [comment]
Merged it. I'll close this issue for now. Let's see how the 'market' responds.
